fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.15.0"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    ruby:    "https://github.com/puppetlabs/puppetlabs-ruby.git"
    gcc:     "https://github.com/puppetlabs/puppetlabs-gcc.git"
    pe_gem:  "https://github.com/puppetlabs/puppetlabs-pe_gem.git"
    make:    "https://github.com/voxpupuli/puppet-make.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    git:     "https://github.com/puppetlabs/puppetlabs-git.git"
    portage:
      repo: "https://github.com/gentoo/puppet-portage.git"
      ref: "2.3.0"
  symlinks:
    r10k:    "#{source_dir}"
